### ISSUE TITLE
Homepage - Header

### ISSUE THREAD

**Issue by dmarkovits** [ThreePillarGlobal/scrumpoker#4]
---------SUMMARY------------

• application header
• logo / app name

------STORY DETAIL--------

As a User, I want an ability to redirect to the Homepage using my app Header so that I can return to Homepage from anywhere within the app. 

• Add the application header
• Add a logo and / or an application name that will redirect to the homepage
• Header will be present on all application views

**Comment by ghost** [comment]
As far as I know, this is done, as I presented it in the session of last Thursday. @dmarkovits , please close it if you agree.
