### ISSUE TITLE
Homepage - Start New Session

### ISSUE THREAD

**Issue by dmarkovits** [ThreePillarGlobal/scrumpoker#5]
### SUMMARY
- "Create Room" button
- generate session ID & session URL
- redirect to Session Specific Page
### STORY DETAIL

As a ScrumMaster, I want an ability to create a room so that I can invite the team to join in. 
- Add a "Create Room" button on the homepage;
- Clicking on the button will generate a unique session ID and URL pointing to that session;
- Accessing the URL would display the room (session page)
- After clicking the "Create Room" button in the Homepage the session host would automatically be redirected to the session page

**Comment by fjurcovici** [comment]
I'll do the server-side part, if everybody agrees.
